### ISSUE TITLE
CM and ML estimation failed; middle of histogram is nonnormal

### ISSUE THREAD

**Issue by simonisphording** [raphael-group/netmix2#2]
After installing all required packages in a new conda environment, the command described under "testing netmix2" returns an error:

locfdr.EstimationError: 'CM and ML estimation failed; middle of histogram is nonnormal.'

**Comment by simonisphording** [comment]
The problem seems to be with the way genes with a p-value of 1 are handled when calculating z-scores. If there are a lot of them, locfdr will not work

**Comment by dah77** [comment]
I get the same error. After installing the dependencies and running the test command with the provided test data:

<code>python run_netmix2.py -el data/edge_list.tsv -gs data/gene_scores.tsv -o results/example_output.tsv</code>

I also get this error:

<code>locfdr.EstimationError: 'CM and ML estimation failed; middle of histogram is nonnormal.'</code>

**Comment by pty0111** [comment]
Thank you for pointing this out. This issue was due to an error in the example gene scores file and has been resolved.
